#!/bin/bash
source ~/.bash_profile
cd ${JLAB_INSTALL_DIR}; source setup_cdet_pd.sh
cd ${JLAB_INSTALL_DIR}/git-repo/sbs_devel/SBS-offline
cd ../build
echo "Current build directory: "
pwd
make install -j8
cd ../SBS-offline